version: "3.9"

services:
  postgres-balance:
    image: postgres
    environment:
      POSTGRES_DB: "balancedb"
      POSTGRES_USER: "balanceuser"
      POSTGRES_PASSWORD: "balancepassword"
    ports:
      - 6432:5432