// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/artnikel/BalanceService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

// BalanceOperation provides a mock function with given fields: ctx, balance
func (_m *BalanceRepository) BalanceOperation(ctx context.Context, balance *model.Balance) error {
	ret := _m.Called(ctx, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Balance) error); ok {
		r0 = rf(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, bId
func (_m *BalanceRepository) GetBalance(ctx context.Context, bId uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, bId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, bId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBalanceRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalanceRepository(t mockConstructorTestingTNewBalanceRepository) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
