// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/artnikel/BalanceService/proto"
)

// BalanceServiceClient is an autogenerated mock type for the BalanceServiceClient type
type BalanceServiceClient struct {
	mock.Mock
}

// BalanceOperation provides a mock function with given fields: ctx, in, opts
func (_m *BalanceServiceClient) BalanceOperation(ctx context.Context, in *proto.BalanceOperationRequest, opts ...grpc.CallOption) (*proto.BalanceOperationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.BalanceOperationResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BalanceOperationRequest, ...grpc.CallOption) *proto.BalanceOperationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BalanceOperationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.BalanceOperationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalance provides a mock function with given fields: ctx, in, opts
func (_m *BalanceServiceClient) GetBalance(ctx context.Context, in *proto.GetBalanceRequest, opts ...grpc.CallOption) (*proto.GetBalanceResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetBalanceResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetBalanceRequest, ...grpc.CallOption) *proto.GetBalanceResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetBalanceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetBalanceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBalanceServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalanceServiceClient creates a new instance of BalanceServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalanceServiceClient(t mockConstructorTestingTNewBalanceServiceClient) *BalanceServiceClient {
	mock := &BalanceServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
